/* eslint-disable react-hooks/refs */
"use client";
import { DndContext, PointerSensor, useDraggable, useDroppable, useSensor, useSensors, type DragEndEvent } from "@dnd-kit/core";
import { CSS } from "@dnd-kit/utilities";
import { useState } from "react";
import { moveTaskAction, updateTaskVisibilityAction } from "@/app/panel/actions";
type Task = { id: string; title: string; description: string | null; column: "todo" | "doing" | "review" | "done"; isPublic: boolean; position: number };
const columns = { todo: "Do zrobienia", doing: "W toku", review: "Do akceptacji", done: "Gotowe" } as const;
function Card({ task, projectId }: { task: Task; projectId: string }) { const drag = useDraggable({ id: task.id, data: { task } }); const style = { transform: CSS.Translate.toString(drag.transform) }; return <article ref={drag.setNodeRef} style={style} {...drag.listeners} {...drag.attributes} className="cursor-grab border-l-4 border-rust bg-paper p-4 shadow-sm active:cursor-grabbing"><p className="font-bold">{task.title}</p>{task.description && <p className="mt-2 text-sm text-ink/60">{task.description}</p>}<form action={updateTaskVisibilityAction} onPointerDown={(e) => e.stopPropagation()} className="mt-3 flex items-center gap-2 text-xs"><input type="hidden" name="id" value={task.id} /><input type="hidden" name="projectId" value={projectId} /><input name="isPublic" type="checkbox" defaultChecked={task.isPublic} /><span>Widoczne dla klienta</span><button className="ml-auto text-rust">Zapisz</button></form></article>; }
function Column({ column, tasks, projectId }: { column: keyof typeof columns; tasks: Task[]; projectId: string }) { const drop = useDroppable({ id: column }); return <section ref={drop.setNodeRef} className={`min-h-52 bg-ink/5 p-3 ${drop.isOver ? "ring-2 ring-rust" : ""}`}><h3 className="mb-4 flex justify-between font-bold"><span>{columns[column]}</span><span className="font-mono text-xs text-ink/40">{tasks.length}</span></h3><div className="grid gap-3">{[...tasks].sort((a,b) => a.position-b.position).map((task) => <Card key={task.id} task={task} projectId={projectId} />)}</div></section>; }
export default function KanbanBoard({ initialTasks, projectId }: { initialTasks: Task[]; projectId: string }) { const [tasks, setTasks] = useState(initialTasks); const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 6 } })); async function end(event: DragEndEvent) { const column = event.over?.id as Task["column"] | undefined; if (!column || !(column in columns)) return; const id = String(event.active.id); const position = Date.now(); setTasks((state) => state.map((task) => task.id === id ? { ...task, column, position } : task)); await moveTaskAction(id, projectId, column, position); } return <DndContext sensors={sensors} onDragEnd={end}><div className="grid gap-4 lg:grid-cols-4">{(Object.keys(columns) as Task["column"][]).map((column) => <Column key={column} column={column} tasks={tasks.filter((task) => task.column === column)} projectId={projectId} />)}</div></DndContext>; }
