"use client";
import { useState, type FormEvent } from "react";
import { authClient } from "@/lib/auth-client";
export default function LoginForm() {
  const [step, setStep] = useState<"password" | "totp">("password"); const [error, setError] = useState(""); const [pending, setPending] = useState(false);
  async function login(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(""); const fd = new FormData(event.currentTarget); const result = await authClient.signIn.email({ email: String(fd.get("email")), password: String(fd.get("password")), rememberMe: false }); setPending(false); if (result.error) return setError("Nieprawidłowy e-mail lub hasło."); if ((result.data as { twoFactorRedirect?: boolean } | null)?.twoFactorRedirect) return setStep("totp"); window.location.href = "/panel"; }
  async function verify(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); const code = String(new FormData(event.currentTarget).get("code")); const result = await authClient.twoFactor.verifyTotp({ code, trustDevice: false }); setPending(false); if (result.error) return setError("Kod jest nieprawidłowy lub wygasł."); window.location.href = "/panel"; }
  return <form onSubmit={step === "password" ? login : verify} className="mt-10 grid gap-5">{step === "password" ? <><label><span className="mb-2 block text-sm font-bold">E-mail administratora</span><input className="admin-field" name="email" type="email" required autoComplete="username" /></label><label><span className="mb-2 block text-sm font-bold">Hasło</span><input className="admin-field" name="password" type="password" required autoComplete="current-password" /></label></> : <label><span className="mb-2 block text-sm font-bold">Kod z aplikacji uwierzytelniającej</span><input className="admin-field text-center font-mono text-2xl tracking-[.3em]" name="code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} required autoFocus /></label>}{error && <p role="alert" className="border-l-4 border-red-500 bg-red-50 p-3 text-sm text-red-800">{error}</p>}<button disabled={pending} className="bg-rust px-6 py-3 font-bold text-paper disabled:opacity-50">{pending ? "Sprawdzanie…" : step === "password" ? "Zaloguj się" : "Potwierdź kod"}</button></form>;
}
