"use client";
import Image from "next/image";
import { useRef, useState, type FormEvent } from "react";
import type { SiteContent } from "@/lib/content";
import { track } from "./Analytics";

export default function Cta({ content }: { content: SiteContent["contact"] }) {
  const started = useRef(false); const [state, setState] = useState<{ pending: boolean; message: string; ok: boolean }>({ pending: false, message: "", ok: false });
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setState({ pending: true, message: "", ok: false }); const form = event.currentTarget; const data = new FormData(form);
    try { const response = await fetch("/api/contact", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: data.get("name"), email: data.get("email"), message: data.get("message"), website: data.get("website"), consent: data.get("consent") === "on" }) }); const result = await response.json(); setState({ pending: false, message: result.message, ok: response.ok }); if (response.ok) { form.reset(); track("form_submit"); } } catch { setState({ pending: false, message: "Nie udało się połączyć z serwerem.", ok: false }); }
  }
  return <section id="kontakt" className="relative overflow-hidden bg-ink"><Image src="/img/keyboard.png" alt="" fill quality={68} sizes="100vw" className="object-cover opacity-70" /><div className="absolute inset-0 bg-gradient-to-r from-ink/95 via-ink/70 to-ink/40" /><div className="relative z-10 mx-auto grid max-w-7xl items-center gap-12 px-6 py-20 sm:px-10 sm:py-28 lg:grid-cols-2"><div className="text-paper"><h2 className="display text-3xl sm:text-5xl">{content.title.split("\n").map((line) => <span className="block" key={line}>{line}</span>)}</h2><p className="mt-5 max-w-md text-paper/80">{content.description}</p></div><form onSubmit={submit} onFocus={() => { if (!started.current) { started.current = true; track("form_start"); } }} className="rounded-3xl bg-paper/10 p-6 backdrop-blur-md sm:p-8"><div className="grid gap-4"><label><span className="mb-1.5 block text-sm text-paper/80">Imię i nazwisko</span><input name="name" required minLength={2} maxLength={120} autoComplete="name" className="form-field" /></label><label><span className="mb-1.5 block text-sm text-paper/80">Adres e-mail</span><input name="email" type="email" required maxLength={255} autoComplete="email" className="form-field" /></label><label><span className="mb-1.5 block text-sm text-paper/80">Wiadomość</span><textarea name="message" required minLength={10} maxLength={5000} rows={4} className="form-field resize-none" /></label><label className="hidden" aria-hidden="true">Strona<input name="website" tabIndex={-1} autoComplete="off" /></label><label className="flex items-start gap-3 text-sm text-paper/75"><input name="consent" type="checkbox" required className="mt-1 accent-[#bd4a2b]" />Zgadzam się na przetwarzanie danych w celu odpowiedzi na zapytanie.</label><button disabled={state.pending} className="rounded-full bg-rust py-3.5 text-lg font-semibold text-paper hover:bg-rust-dark disabled:opacity-50">{state.pending ? "Wysyłanie…" : "Wyślij wiadomość"}</button>{state.message && <p role="status" className={state.ok ? "text-green-300" : "text-red-300"}>{state.message}</p>}</div></form></div></section>;
}
