import { desc, gte } from "drizzle-orm";
import { requireAdmin } from "@/lib/admin";
import { db } from "@/lib/db";
import { analyticsEvents } from "@/lib/db/schema";
import { analyticsReport } from "@/lib/analytics-report";
import PanelShell from "@/components/admin/PanelShell";
export const dynamic = "force-dynamic";
function since(days: number) { return new Date(new Date().getTime() - days * 86_400_000); }
export default async function AnalyticsPage({ searchParams }: { searchParams: Promise<{ days?: string }> }) { await requireAdmin(); const params = await searchParams; const days = [7, 30, 90, 365].includes(Number(params.days)) ? Number(params.days) : 30; const rows = await db.select().from(analyticsEvents).where(gte(analyticsEvents.createdAt, since(days))).orderBy(desc(analyticsEvents.createdAt)); const report = analyticsReport(rows); const cards = [["Odsłony", report.views], ["Unikalne sesje", report.sessions], ["Wysłane formularze", report.submissions], ["Konwersja", `${report.conversion}%`]]; return <PanelShell title="Statystyki" eyebrow={`Ostatnie ${days} dni`}><div className="mb-6 flex flex-wrap gap-2">{[7,30,90,365].map((value) => <a key={value} href={`/panel/analytics?days=${value}`} className={`px-4 py-2 text-sm font-bold ${value === days ? "bg-rust text-paper" : "bg-paper"}`}>{value} dni</a>)}<a href={`/api/admin/analytics.csv?days=${days}`} className="ml-auto border border-ink px-4 py-2 text-sm font-bold">Eksport CSV</a></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value]) => <article key={label} className="border-t-4 border-rust bg-paper p-6"><p className="text-sm font-bold uppercase text-ink/50">{label}</p><p className="display mt-4 text-5xl">{value}</p></article>)}</div><div className="mt-8 grid gap-6 lg:grid-cols-3">{[["Urządzenia", report.devices], ["Źródła", report.sources], ["Kliknięcia CTA", report.labels]].map(([title, data]) => <section key={title as string} className="bg-paper p-6"><h2 className="text-xl font-bold">{title as string}</h2><div className="mt-5 space-y-3">{(data as [string, number][]).slice(0, 10).map(([label, value]) => <div key={label}><div className="flex justify-between text-sm"><span>{label}</span><strong>{value}</strong></div><div className="mt-1 h-2 bg-mist"><div className="h-full bg-rust" style={{ width: `${Math.max(4, value / Math.max(...(data as [string,number][]).map((x) => x[1])) * 100)}%` }} /></div></div>)}{!(data as unknown[]).length && <p className="text-ink/50">Brak danych.</p>}</div></section>)}</div></PanelShell>; }
